USE IF6201_EX2_DW_B97452
GO

CREATE SCHEMA DW
GO

CREATE TABLE DW.DIM_PELICULAS
(
	ID INT PRIMARY KEY,
	CODIGO VARCHAR(100) NULL,
	NOMBRE VARCHAR(75) NULL,
	PRECIO VARCHAR(15) NULL,
	IDIOMA VARCHAR(50) NULL,
	LANZAMIENTO DATE NULL
)
GO

CREATE TABLE DW.DIM_CLIENTE
(
	ID INT PRIMARY KEY,
	NOMBRE VARCHAR(50) NULL
)
GO

CREATE TABLE DW.DIM_VENTAS
(
	ID INT PRIMARY KEY,
	TOTAL VARCHAR(50) NULL,
	CANTIDAD INT NULL
)
GO

CREATE TABLE DW.DIM_TIEMPO
(
	ID INT PRIMARY KEY,
	FECHA_VENTA DATETIME NULL,
	ANIO_VENTA INT NULL,
	MES_VENTA INT NULL,
	DIA_VENTA INT NULL
)
GO

CREATE TABLE DW.DIM_HECHOS
(
	DIM_ID_PELICULA INT,
	DIM_ID_CLIENTE INT,
	DIM_ID_VENTA INT,
	DIM_ID_TIEMPO INT,
	TOTAL_PELICULAS_VENDIDAS INT,
	TOTAL_VENTAS_REALIZADAS INT,
	CONSTRAINT PK_HECHOS PRIMARY KEY (DIM_ID_PELICULA, DIM_ID_CLIENTE, DIM_ID_VENTA, DIM_ID_TIEMPO),
	CONSTRAINT FK_PELICULA FOREIGN KEY (DIM_ID_PELICULA) REFERENCES DW.DIM_PELICULAS(ID),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (DIM_ID_CLIENTE) REFERENCES DW.DIM_CLIENTE(ID),
	CONSTRAINT FK_VENTA FOREIGN KEY (DIM_ID_VENTA) REFERENCES DW.DIM_VENTAS(ID),
	CONSTRAINT FK_TIEMPO FOREIGN KEY (DIM_ID_TIEMPO) REFERENCES DW.DIM_TIEMPO(ID)
)
GO

----------------------------------------------------------------


SELECT 
	V.ID AS ID_VENTA,
	P.ID AS ID_PELICULA,
	C.ID AS ID_CLIENTE,
	V.ID AS ID_TIEMPO,
	SUM(V.CANTIDAD) OVER(PARTITION BY P.ID) AS TOTAL_PELICULA_VENDIDA,
	COUNT(V.ID_CLIENTE) OVER(PARTITION BY C.ID) AS TOTAL_COMPRAS_REALIZADAS_CLIENTE
FROM [PELICULAS].[tb_VENTAS] V
	JOIN [PELICULAS].[tb_PELICULAS] P
		ON V.ID_PELICULA = P.ID
		JOIN [PELICULAS].[tb_CLIENTE] C
			ON V.ID_CLIENTE = C.ID